package com.blockverse.app.enums;

public enum AuditActionType {
    WORKSPACE_CREATED,
    WORKSPACE_DELETED,
    WORKSPACE_RESTORED,
    WORKSPACE_OWNERSHIP_TRANSFERRED,
    DOCUMENT_CREATED,
    DOCUMENT_DELETED,
    DOCUMENT_RESTORED,
    DOCUMENT_UPDATED,
    DOCUMENT_ARCHIVED,
    DOCUMENT_UNARCHIVED,
    BLOCK_CREATED,
    BLOCK_UPDATED,
    BLOCK_DELETED,
    BLOCK_MOVED,
    USER_ADDED,
    USER_REMOVED,
    USER_LEFT,
    USER_INVITED,
    DOCUMENT_PERMANENTLY_DELETED, ROLE_CHANGED
}
